// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1bMsm3M4pLONLUevH5Tg3FMJLgRNqVk',
    appId: '1:145334725425:android:8d6d8378cde15fd80a1e10',
    messagingSenderId: '145334725425',
    projectId: 'uni-pay-eb481',
    storageBucket: 'uni-pay-eb481.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjaa4sLaj8TAWEzVyF9KlKLejRn9cVFw',
    appId: '1:145334725425:web:803889a2131a0d1e0a1e10',
    messagingSenderId: '145334725425',
    projectId: 'uni-pay-eb481',
    authDomain: 'uni-pay-eb481.firebaseapp.com',
    storageBucket: 'uni-pay-eb481.firebasestorage.app',
    measurementId: 'G-Y3F328CVXF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJeinkZLCCYaEcYg_o0be0dPEzEIu8OX4',
    appId: '1:145334725425:ios:6d4c384169e0385f0a1e10',
    messagingSenderId: '145334725425',
    projectId: 'uni-pay-eb481',
    storageBucket: 'uni-pay-eb481.firebasestorage.app',
    iosBundleId: 'com.example.fastnew',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeinkZLCCYaEcYg_o0be0dPEzEIu8OX4',
    appId: '1:145334725425:ios:6d4c384169e0385f0a1e10',
    messagingSenderId: '145334725425',
    projectId: 'uni-pay-eb481',
    storageBucket: 'uni-pay-eb481.firebasestorage.app',
    iosBundleId: 'com.example.fastnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJjaa4sLaj8TAWEzVyF9KlKLejRn9cVFw',
    appId: '1:145334725425:web:74d4a215765ef08c0a1e10',
    messagingSenderId: '145334725425',
    projectId: 'uni-pay-eb481',
    authDomain: 'uni-pay-eb481.firebaseapp.com',
    storageBucket: 'uni-pay-eb481.firebasestorage.app',
    measurementId: 'G-7QVM47B9XE',
  );

}